services:
  influxdb:
    image: influxdb:1.8
    platform: linux/amd64
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_HTTP_AUTH_ENABLED: "false"

  grafana:
    image: grafana/grafana:8.5.0
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: skeleton

  k6:
    image: grafana/k6:v0.40.0
    platform: linux/amd64
    depends_on:
      - influxdb
    volumes:
      - ./k6.js:/k6.js
    command: run --out influxdb=http://influxdb:8086/k6 /k6.js
